import itertools, os, sys
from collections import abc, deque

class State(str):
    def __new__(cls, state: str):
        return super().__new__(cls, f"STATE_{state}")

class Action(str):
    def __new__(cls, action: str):
        return super().__new__(cls, f"FSM_{action}")

def parse_int(s: str) -> int:
    if s.startswith("'"):
        assert len(s) == 3, f"Invalid input: {s}"
        return ord(s[1])
    return int(s, 16) if s.startswith("0x") else int(s)

def interp(line: str) -> abc.Iterable[State | tuple[int, State, Action]]:
    if not line.strip():
        return

    match (ll := deque(line.split())).popleft():
        case "anywhere":
            yield State("anywhere")
        case "state":
            yield State(ll.popleft())
        case "input":
            num = parse_int(ll.popleft())
            _ = ll.popleft() # arrow.
            yield (num, State(ll.popleft()), Action(ll.popleft()))
        case "range":
            fst, snd = parse_int(ll.popleft()), parse_int(ll.popleft())
            _ = ll.popleft() # arrow.
            state, action = State(ll.popleft()), Action(ll.popleft())
            yield from ((num, state, action) for num in range(fst, snd+1))
        case "default":
            _ = ll.popleft() # arrow.
            yield (0xff, State(ll.popleft()), Action(ll.popleft()))

def generate() -> dict[State, list[tuple[State, Action]]]:
    table, state  = {}, State("ground")
    for line in sys.stdin:
        for event in interp(line):
            match event:
                case State(new):
                    state = event
                    if table.get(state, None) is None:
                        table[state] = [None] * 0x100
                case (ch, next_state, action):
                    if table[state][ch] is None:
                        table[state][ch] = (next_state, action)
    return table

if __name__ == "__main__":
    table = generate()

    global_rules = table.get(State("anywhere"), [])
    if State("anywhere") in table:
        del table[State("anywhere")]

    for key in table.keys():
        for ch, rule in enumerate(global_rules):
            if table[key][ch] is None:
                table[key][ch] = rule

    m = max(map(lambda x: len(x), table.keys()))
    all_actions = filter(lambda x: x is not None, itertools.chain(*table.values()))
    unique_actions = sorted(set(map(lambda x: x[1], all_actions)))

    print("// This is file is auto-generated, **DO NOT EDIT THIS FILE BY HAND!.**.")
    print("//")
    print("#include <stdint.h>")
    print()

    print("typedef enum FSM_State {")
    states = "\n".join(map(lambda x: f"    {f"{x[1]}":<{m}} = {x[0]},", enumerate(table.keys(), 1)))
    print(states)
    print("} FSM_State;")
    print()

    print("typedef enum FSM_Action {")
    ma = max(map(lambda x: len(x), unique_actions))
    actions = "\n".join(map(lambda x: f"    {f"{x[1]}":<{ma}} = {x[0]},", enumerate(unique_actions, 1)))
    print(actions)
    print("} FSM_Action;")
    print()

    print("typedef uint16_t FSM_Effect;")
    print("#define fsm_state(effect)  (((effect) >> 8) & 0x7f)")
    print("#define fsm_action(effect) ((effect) & 0x7f)")
    print()

    print(f"{"#define pack(state, action)":<79}\\")
    print("    ((uint16_t)(((uint16_t)(state) << 8) | (uint16_t)(action)))")
    print()

    print("static const FSM_Effect default_transition[] = {")
    for state in table.keys():
        if (default := table[state][0xff]) is not None:
            next_state, action = default
            print(f"    {f"[{state}]":<{m+2}} = pack({next_state}, {action}),")
    print("};")
    print()

    print("static const FSM_Effect transition_table[][256] =")
    print("    {")
    for state, transitions in table.items():
        if any(map(lambda t: t is not None, transitions[:-1])):
            print(f"        [{state}] =")
            print("            {")
            for ch, transition in enumerate(transitions[:-1]):
                if transition is not None:
                    next_state, action = transition
                    print(f"                {f"[{ch:#02x}]":<6} = pack({next_state}, {action}),")
            print("            },")
    print("};")
    print()

    print("#undef pack")
